local blueprint = {
    category = "modules",
    id = "ability_afterburner",
    name = "Aurora Afterburner",
    slot = "ability",
    rarity = "rare",
    description = "Ability module that floods the engines for a sustained afterburn boost.",
    components = {
        module = {
            ability = {
                id = "afterburner",
                type = "afterburner",
                displayName = "Afterburner",
                continuous = true,
                duration = 0.35,
                energyPerSecond = 32,
                thrustMultiplier = 1.65,
                strafeMultiplier = 1.4,
                reverseMultiplier = 1.25,
                accelerationMultiplier = 1.6,
                maxSpeedMultiplier = 1.55,
                trailDuration = 0.5,
                trailFade = 0.4,
                trailStrength = 1.6,
                trailBurstParticles = 200,
                trailBurstStrength = 1.4,
                zoomMultiplier = 0.55,
                minZoom = 0.3,
                maxZoom = 2.5,
                sfx = "sfx:engine_afterburn",
                sfxPitch = 1.05,
                sfxVolume = 0.95,
                hotkeyLabel = "SPACE",
                intentIndex = 1,
            },
        },
    },
    icon = {
        kind = "module",
        color = { 0.25, 0.6, 1.0, 1.0 },
        accent = { 0.12, 0.32, 0.85, 1.0 },
        detail = { 0.72, 0.92, 1.0, 1.0 },
        layers = {
            { shape = "rounded_rect", width = 0.82, height = 0.42, color = { 0.04, 0.08, 0.16 }, alpha = 0.95, radius = 0.12 },
            { shape = "triangle", width = 0.46, height = 0.78, color = { 0.28, 0.66, 1.0 }, alpha = 0.88, direction = "up" },
            { shape = "triangle", width = 0.32, height = 0.56, color = { 0.85, 0.98, 1.0 }, alpha = 0.74, direction = "up" },
            { shape = "ring", radius = 0.5, thickness = 0.07, color = { 0.16, 0.38, 0.92 }, alpha = 0.7 },
            { shape = "burst", radius = 0.72, color = { 0.3, 0.75, 1.0 }, alpha = 0.38 },
        },
    },
    item = {
        name = "Aurora Afterburner",
        description = "Trigger to overcharge your thrusters, boosting speed and widening tactical view.",
        value = 3200,
        volume = 6,
    },
}

return blueprint
